ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION

LABEL maintainer=$AUTHOR version=$VERSION

ARG TARGETOS
ARG TARGETARCH

ADD ./configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml
ADD ./dist/envoy-$TARGETOS-$TARGETARCH /usr/local/bin/envoy

CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]