FROM golang@sha256:cfc9d1b07b1ef4f7a4571f0b60a99646a92ef76adb7d9943f4cb7b606c6554e2

COPY ./server /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/server
COPY *.go /go/src/github.com/envoyproxy/envoy/example/load-reporting-service/
COPY go.sum /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
COPY go.mod /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

WORKDIR /go/src/github.com/envoyproxy/envoy/example/load-reporting-service
RUN go mod download
RUN go install /go/src/github.com/envoyproxy/envoy/example/load-reporting-service

CMD ["go","run","main.go"]
