name: Check dependencies

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run dependency checker
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          TODAY_DATE=$(date -u -I"date")
          export TODAY_DATE
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c release_issues --fix
          bazel run //tools/dependency:check --action_env=TODAY_DATE -- -c cves -w error
