name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-20.04
    if: github.repository == 'envoyproxy/envoy'
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@6c5ccdad469c9f8a2996bfecaec55a631a347034
